name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build Frontend
        run: |
          cd ruoyi-ui
          npm install --legacy-peer-deps
          npm run build:prod
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Build Backend (Maven)
        run: mvn clean package -DskipTests

      - name: Upload frontend to server
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
            ./ruoyi-ui/dist/ ${{ secrets.USER }}@${{ secrets.HOST }}:/root/ruoyi-ui/

      - name: Upload backend jars to server
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
            ruoyi-auth/target/*.jar \
            ruoyi-gateway/target/*.jar \
            ruoyi-visual/ruoyi-monitor/target/*.jar \
            ruoyi-modules/ruoyi-system/target/*.jar \
            ruoyi-modules/ruoyi-gen/target/*.jar \
            ruoyi-modules/ruoyi-job/target/*.jar \
            ruoyi-modules/ruoyi-file/target/*.jar \
            ${{ secrets.USER }}@${{ secrets.HOST }}:/root/ruoyi-backend/

      - name: Restart backend services
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
            echo "Stopping old services..."
            pkill -f 'java.*jar' || true
            echo "Starting new services..."
            for jar in /root/ruoyi-backend/*.jar; do
              nohup java -jar "$jar" > /dev/null 2>&1 &
            done
            echo "All backend services restarted."
          EOF
        env:
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}
