name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
  
      - name: Build Frontend
        run: |
          cd ruoyi-ui
          npm install --legacy-peer-deps
          npm run build:prod 
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Build backend
        run: |
          mvn clean package -DskipTests

      - name: Deploy to Server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ruoyi-ui/dist/ root@60.204.213.152:/root/ruoyi-ui/
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ruoyi-modules/target/*.jar root@60.204.213.152:/root/ruoyi-backend/
        env:
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}

      - name: Restart backend services
        run: |
          ssh -o StrictHostKeyChecking=no root@60.204.213.152 "
            pkill -f 'java.*jar'
            nohup java -jar /home/youruser/ruoyi-backend/xxx.jar > /dev/null 2>&1 &
          "
