name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build frontend
        run: |
          cd ruoyi-ui
          npm install
          npm run build

      - name: Build backend
        run: |
          mvn clean package -DskipTests

      - name: Upload files to server
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./dist root@60.204.213.152:/root/ruoyi-ui
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ruoyi-modules/target/*.jar root@60.204.213.152:/root/ruoyi-backend

      - name: Restart backend services
        run: |
          ssh -o StrictHostKeyChecking=no root@60.204.213.152 "
            pkill -f 'java.*jar'
            nohup java -jar /home/youruser/ruoyi-backend/xxx.jar > /dev/null 2>&1 &
          "
